data_root: "../../data/UCSF-PDGM"
output_dir: "./output"
output_name: "eval-complete"
seed: 42
os_bins: 4 
age_bins: [0, 60, 100]
reconstruction: 
  num_samples: 10
  lower_slice: 60
  upper_slice: 130
  sampling_mask: "radial"
  type: "T2"
  pathology: ["edema","non_enhancing"]
  model: 
    - network: "UNet"
      model_path: "./output/unet_20240927_164753/checkpoints/unet_20240927_164753_epoch_20_final.pth"
classifiers:
  lower_slice: 60
  upper_slice: 130
  type: "T2"
  pathology: ["edema","non_enhancing"]
  models: 
    - type: "TGradeBCEClassifier"
      network: "ResNet18"
      model_path: "./output/tgrade_test_20240925_113550/checkpoints/tgrade_test_20240925_113550_epoch_2.pth"
    - type: "TTypeBCEClassifier"
      network: "ResNet18"
      model_path: "./output/ttype_test_20240925_113544/checkpoints/ttype_test_20240925_113544_epoch_2.pth"
    - type: "NLLSurvClassifier"
      network: "ResNet18"
      model_path: "./output/os_20241002_160021/checkpoints/os_20241002_160021_epoch_3.pth"
    - type: "AgeCEClassifier"
      network: "ResNet18"
      model_path: "./output/age_20241002_140224/checkpoints/age_20241002_140224_epoch_1_best.pth"
    - type: "GenderBCEClassifier"
      network: "ResNet18"
      model_path: "./output/gender_20241002_140300/checkpoints/gender_20241002_140300_epoch_1_best.pth"

