data_root: "../../data/UCSF-PDGM"
output_dir: "./output"
output_name: "test-evaluation-new"
number_of_images: 10
reconstruction_model: "../output/recon_test_20240925_090156/checkpoints/recon_test_20240925_090156_epoch_71.pth"
classifiers:
  - type: "TGradeBCEClassifier"
    network: "ResNet18"
    model_path: "./output/tgrade_test_20240925_113550/checkpoints/tgrade_test_20240925_113550_epoch_2.pth"
  - type: "TTypeBCEClassifier"
    network: "ResNet18"
    model_path: "./output/ttype_test_20240925_113544/checkpoints/ttype_test_20240925_113544_epoch_2.pth"
