data_root: "../../data/UCSF-PDGM"
output_dir: "./output"
output_name: "test-evaluation"
number_of_images: 10
reconstruction_model: "/homes9/matteow/code/dfci/output/recon_test_20240925_080957/checkpoints/recon_test_20240925_080957_epoch_3_final.pth"
classifiers:
  - type: "TGradeBCEClassifier"
    network: "ResNet18"
    model_path: "/homes9/matteow/code/dfci/output/test-classifier_20240924_164649/checkpoints/test-classifier_20240924_164649_epoch_11.pth"
