output_dir: './output'
output_name: 'os-18'
save_interval: 1

num_epochs: 20
learning_rate: 0.0001
batch_size: 16
early_stopping_patience: 10
#num_train_samples: 32
#num_val_samples: 32

data_root: '../../data/UCSF-PDGM/'
type: 'T2'
pathology: ["edema","non_enhancing"]
classifier_type: 'NLLSurvClassifier'  # Options: 'TTypeBCEClassifier', 'TGradeBCEClassifier', 'NLLSurvClassifier'
network_type: 'ResNet18'  # Options: 'ResNet18', 'ResNet50'
seed: 31415

#bins: 4
#eps: 1e-8