data_root: "../../data/UCSF-PDGM"
output_dir: "./output"
output_name: "patient_aggregation"
seed: 42
os_bins: 4 
age_bins: [0, 60, 100]
classifiers:
  lower_slice: 60
  upper_slice: 130
  type: "T2"
  pathology: ["edema","non_enhancing"]
  models: 
    - type: "TGradeBCEClassifier"
      network: "ResNet18"
      model_path: "./models/tgrade/checkpoints/tgrade_test_20240925_113550_epoch_1_best.pth"
    - type: "TTypeBCEClassifier"
      network: "ResNet18"
      model_path: "./models/ttype/checkpoints/ttype_test_20240925_113544_epoch_1_best.pth"
    - type: "NLLSurvClassifier"
      network: "ResNet18"
      model_path: "./models/os18/checkpoints/os_20241003_235554_epoch_1_best.pth"
    - type: "AgeCEClassifier"
      network: "ResNet18"
      model_path: "./models/age/checkpoints/age-60_20241007_103705_epoch_1_best.pth"
    - type: "GenderBCEClassifier"
      network: "ResNet18"
      model_path: "./models/gender/checkpoints/gender_20241002_140300_epoch_1_best.pth"

