output_dir: './output'
output_name: 'tgrade'
save_interval: 3

num_epochs: 20
learning_rate: 0.0001
batch_size: 16
early_stopping_patience: 5

data_root: '../../data/UCSF-PDGM/processed/'
log_dir: './runs'

classifier_type: 'TGradeBCEClassifier'  # Options: 'TTypeBCEClassifier', 'TGradeBCEClassifier', 'NLLSurvClassifier'
network_type: 'ResNet18'  # Options: 'ResNet18', 'ResNet50'
seed: 31415

#bin_size: 250
#eps: 1e-8
