output_dir: './output'
output_name: 'unet'
save_interval: 1

num_epochs: 100
learning_rate: 0.0001
batch_size: 10

data_root: '../../data/UCSF-PDGM'
type: 'T2'
num_val_samples: 10
num_train_samples: 1000
lower_slice: 60
upper_slice: 130

network_type: 'unet'
sampling_mask: 'radial'
seed: 31415
