output_dir: './output'
output_name: 'vgg'
save_interval: 1

num_epochs: 20
learning_rate: 0.0001
batch_size: 8

data_root: '../../data/UCSF-PDGM'
type: 'T2'
lower_slice: 60
upper_slice: 130

network_type: 'VGG'  # Options: 'VGG'
network_path: './models/imagenet-vgg16.pth'
sampling_mask: 'radial'
seed: 31415
